[package]
name = "nts"
version = "0.1.0"
authors = ["Watson Ladd <watson@cloudflare.com>", "Gabbi Fisher <gabbi@cloudflare.com>"]
edition = "2018"

[dependencies]
byteorder="1.3.1"
clap = "2.32.0"
config = "0.9"
lazy_static="1.3.0"
libc = "0.2.49"
log="0.4.6"
memcache = "0.12.1"
mio = "0.6.16"
miscreant = "0.4.2"
prometheus = "0.5"
rand = "0.6.5"
ring = "0.14.6"
rustls = "0.15.1"
simple_logger="1.0.1"
slog= { version = "2.4.1", features = ["max_level_trace", "release_max_level_debug"]} # We configure at runtime
slog-scope="4.1.1"
slog-stdlog="3.0.2"
sloggers="0.3.2"
webpki = "0.19.1"
webpki-roots="0.16.0"

[source.crates-io]
replace-with = "vendored-sources"

[source.vendored-sources]
directory = "/Users/watsonladd/cf-repos/nts/vendor"