[package]
name = "nts"
version = "0.1.0"
authors = ["Watson Ladd <watson@cloudflare.com>", "Gabbi Fisher <gabbi@cloudflare.com>"]
edition = "2018"

[dependencies]
byteorder="1.3.1"
clap = "2.32.0"
config = "0.9"
futures = "0.1"
libc = "0.2.49"
log="0.4"
simple_logger="1.0.1"
memcache = "0.12.1"
mio = "0.6.16"
miscreant = "0.4.2"
prometheus = "0.5"
rand = "0.6.5"
ring = "0.14.6"
rustls = "0.15.1"
tokio = "0.1.15"
tokio-rustls = "0.10.0-alpha"
webpki = "0.19.1"
webpki-roots="0.16.0"

[source.crates-io]
replace-with = "vendored-sources"

[source.vendored-sources]
directory = "/Users/watsonladd/cf-repos/nts/vendor"