[package]
name        = "nts"
version     = "2019.6.0"
authors = [
    "Watson Ladd <watson@cloudflare.com>",
    "Gabbi Fisher <gabbi@cloudflare.com>",
    "Tanya Verma <tverma@cloudflare.com>",
    "Suphanat Chunhapanya <pop@cloudflare.com>",
]
edition     = "2018"

[dependencies]

byteorder   = "1.3.1"

# Used for command-line parsing and validation.
clap        = "2.32.0"

config      = "0.9"
crossbeam   = "0.6.0"
lazy_static = "1.3.0"
libc        = "0.2.49"
log         = "0.4.6"
memcache    = "0.12.1"
mio         = "0.6.16"
miscreant   = "0.4.2"
net2        = "0.2.33"
nix         = "0.13.0"
prometheus  = "0.5.0"
rand        = "0.6.5"
ring        = "0.14.6"
rustls      = "0.15.1"
simple_logger = "1.0.1"

# More advanced logging system than `log`.
slog = { version = "2.4.1", features = [
    "max_level_trace",
    "release_max_level_debug",
]} # We configure at runtime

# Add scopes to the logging system.
slog-scope  = "4.1.1"

# Used for fowarding all the `log` crate logging to `slog_scope::logger()`.
slog-stdlog = "3.0.2"

# A wrapper of `slog` to make logging more convenient.
sloggers    = "0.3.2"

webpki      = "0.19.1"
webpki-roots = "0.16.0"
