version: "3"
services:
  server:
    build:
      context: .
      dockerfile: Dockerfile.server
    depends_on:
      - memcache
  client:
    build:
      context: .
      dockerfile: Dockerfile.client
    depends_on:
      - server
  memcache:
    build:
      context: .
      dockerfile: Dockerfile.memcache
