version: 2
jobs:
  build:
    docker:
    - image: circleci/rust:1.35.0-stretch
    steps:
    - checkout
    - run:
        name: Version
        command: rustc --version; cargo --version; rustup --version
    - run:
        name: Compiling
        command: cargo build --release
    - run:
        name: Running tests
        command: cargo test --release
workflows:
  main:
    jobs:
    - build
  version: 2
