version: 2.0
jobs:
  build:
    docker:
      - image: circleci/rust:1.35.0-stretch
    steps:
      - checkout
      - run: 
          name: "Vendoring"
          command: |
            wget https://github.com/alexcrichton/cargo-vendor/releases/download/0.1.23/cargo-vendor-0.1.23-x86_64-unknown-linux-musl.tar.gz
            tar xfz cargo-vendor-0.1.23-x86_64-unknown-linux-musl.tar.gz
            cargo-vendor-0.1.23-x86_64-unknown-linux-musl/cargo-vendor vendor >> .cargo/config
      - run:
          name: "Run tests"
          command:
            cargo test
workflows:
  "main":
    jobs:
      - build
